app = 'formmy-v2'
primary_region = 'dfw'

[build]
  # Builder con más recursos para builds rápidos
  builder = "paketobuildpacks/builder-jammy-buildpackless-full"

[deploy]
  # Deploy más rápido con menos verificaciones
  wait_timeout = "5m"
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# VM más grande para builds rápidos
[[vm]]
  size = 'shared-cpu-2x'
  memory = 1024
  
[env]
  NODE_ENV = "production"
  PORT = "3000"
  
